ARG NODE_VERSION=18
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json .
RUN yarn install

COPY . .

RUN yarn lerna bootstrap

RUN rm -rf /app/packages/server/dist/ && yarn build --scope server


FROM node:$NODE_VERSION-buster-slim as production
WORKDIR /app

COPY --from=builder /app/packages/server/dist/ /app/
COPY --from=builder /app/packages/server/package.json /app/package.json
RUN yarn install

EXPOSE $SERVER_PORT
CMD [ "yarn", "/app/index.js" ]
