ARG NODE_VERSION=18
ARG SERVER_PORT=3001
FROM node:$NODE_VERSION-buster-slim

WORKDIR ./var/app

COPY ./packages/server .

RUN yarn install

RUN yarn build

RUN ls | grep -v dist | grep -v node_modules | xargs rm -rfv

WORKDIR ./dist

EXPOSE $SERVER_PORT

CMD [ "node", "index.js" ]
