FROM node:18-alpine as build

WORKDIR ./var/app

COPY ./packages/server .


RUN yarn install && yarn rimraf dist

RUN yarn build

RUN ls | grep -v dist | grep -v node_modules | xargs rm -rfv

WORKDIR ./dist

EXPOSE $SERVER_PORT

CMD [ "node", "index.js" ]
