name: Push To Yandex Cloud CR
on:

  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpe70i40r7a5a94kugj
          CR_REPOSITORY: github.com/5dev-team/BattleCity
          IMAGE_TAG: ${{ github.sha }}
          CLIENT_PORT: 3000
          SERVER_PORT: 3000
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
          YANDEX_API: http://localhost:3000/api/v2
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: secret
          PGADMIN_LISTEN_PORT: 80
          NODE_ENV: production
          YANDEX_OAUTH_URL: https://oauth.yandex.ru/authorize
          YANDEX_REDIRECT_URI: http://localhost:3000
          DOMAIN: localhost
        run: |
          docker compose build
          docker tag server:latest cr.yandex/$CR_REGISTRY/server:latest
          docker tag postgres:14 cr.yandex/$CR_REGISTRY/postgres:14
          docker tag dpage/pgadmin4:4.18 cr.yandex/$CR_REGISTRY/dpage/pgadmin4:4.18
          docker push cr.yandex/$CR_REGISTRY/server:latest
          docker push cr.yandex/$CR_REGISTRY/postgres:14
          docker push cr.yandex/$CR_REGISTRY/dpage/pgadmin4:4.18
